### ISSUE TITLE
Merhaba

### ISSUE THREAD

**Issue by axen1** [cagoshian/mhrs-otorandevu#1]
hocam İSTANBUL(ANADOLU) yazdığımda terminal se "i" harfini büyük yazdığımız dan dolayı ? işareti alıyor ve sistemden atıyor nasıl yapalım ?

**Comment by cagoshian** [comment]
Hocam plaka koduyla il seçme ekledim. Anadolu/Avrupa yakası ayrımı ise il seçiminde söz konusu değil, yakında ilçe seçimi de eklemeyi planlıyorum, o zaman yapabilirsiniz.

**Comment by axen1** [comment]
Hocam ben onu bi şekilde geçtim ancak klinikte olayını geçemedim "Deri ve Zührevi Hastalıkları (Cildiye)" bunu yazamıyorum ne yapdıysam olmadı.



   const klinikprompt = prompt("Randevu istediğiniz kliniğin adı: ");
const secilenKlinik = klinikler.find(klinik => klinik.text.toLowerCase() === klinikprompt.toLowerCase());

**Comment by cagoshian** [comment]
Hocam ben klinik sorduğunda "cildiye" yazınca direkt Deri ve Zührevi Hastalıkları (Cildiye) seçiyor.
Altta belirttiğiniz kod ile direkt randevu istenen kliniğin tam adını girmek gerekiyor, o da pratikliği ciddi oranda bozar.

**Comment by axen1** [comment]
Hocam test ettim eline sağlık ben bir html yapısı kullanarak sayfa ya bağlayıp geliştirme yapacağım.

**Comment by burhanyldz** [comment]
@cagoshian elinize sağlık hocam, çok makbule geçti.
